- docs/receiving/verifying-payloads/how.mdx
- docusaurus.config.js
- src/theme/CodeTabs.js
> add php & ruby to verification docs

- docs/receiving/verifying-payloads/how.mdx
looks like i missed adding the addn'l tabs to the second row 🙈
> fix verifcation tabs

- docs/receiving/verifying-payloads/how-manual.mdx
- docs/receiving/verifying-payloads/how.mdx
- sidebars.js
> [0.5] Add framework-specific docs for consuming webhooks.

- docs/event-types.mdx
> Event types: explain people should bulk create and show how.

- docs/event-types.mdx
> Add title to bulk create admonition

- docs/management-ui.mdx
> Add blurb about `svix-react` library

- docs/account/environments.mdx
Please merge in once approved, I don't have perms
> Add section on HTTPS Only Endpoints

- docusaurus.config.js
https://user-images.githubusercontent.com/84334931/135515589-2b101e7d-cf50-4a20-908d-322e430053a3.mov
> Add light/dark mode icons to toggle

- docs/integrations/zapier.mdx
> Fix Go example on Zapier docs

- docs/app-portal.mdx
- docs/event-types.mdx
- docs/integrations/zapier.mdx
- docs/quickstart.mdx
- docs/rate-limit.mdx
- docs/receiving/verifying-payloads/how.mdx
- docs/retention.md
- docs/setup.mdx
- docusaurus.config.js
- src/theme/CodeTabs.js
We now have a Rust lib so add code samples everywhere.
> Add Rust examples everywhere.

- docs/app-portal.mdx
- docs/event-types.mdx
- docs/integrations/zapier.mdx
- docs/quickstart.mdx
- docs/rate-limit.mdx
- docs/receiving/verifying-payloads/how.mdx
- docs/retention.md
- docs/setup.mdx
- docusaurus.config.js
- src/theme/CodeTabs.js
We now have a C# lib so add code samples everywhere.
> Add C# examples everywhere.

- docs/common-usage-examples.mdx
- docs/quickstart.mdx
- sidebars.js
This section includes descriptions of some of the common ways people use
Svix (and webhooks in general) and how to model these scenarios in Svix.
> Add a section for common usage examples.

- docs/overview.mdx
> fix environment typo

- docs/quickstart.mdx
This depends on https://github.com/svix/svix-webhooks/pull/571 being
merged and released.
> Qucikstart: mention automatic server URL detection.

- docs/receiving/verifying-payloads/how-manual.mdx
- docs/receiving/verifying-payloads/how.mdx
- docs/receiving/verifying-payloads/why.mdx
adjusted titles of verification articles to make it more obvious what each article is about.
> Clarify titles of signature verification articles

- docs/receiving/verifying-payloads/how-manual.mdx
Updates `"`  to ` for signature concatenation
> Update webhook security guide

- docs/receiving/verifying-payloads/how.mdx
example for using svix in NestJS
> NestJS usage example

- docs/transformations.mdx
This change simply adds one line of documentation noting the new field.
> Add point on cancellation feature of transformations

- docs/receiving/source-ips.mdx
Updates the IP address list to the current set (as per the AWS console), and segmenting the list depending on which region the IPs belong to.
> Update IP address list and group by region

- docs/common-usage-examples.mdx
- docs/integrations/advanced-zapier.mdx
- docs/integrations/ngrok.mdx
- docs/integrations/zapier.mdx
- docs/overview.mdx
- docs/play.mdx
- docs/quickstart.mdx
- docs/receiving/using-app-portal/filtering-logs.mdx
- docs/receiving/using-app-portal/testing-events.mdx
- docs/receiving/verifying-payloads/how.mdx
- docs/tutorials/cli.mdx
- docs/tutorials/event-type-schema.mdx
> Docs: fix a few minor typos

- docs/transformations.mdx
related https://github.com/svix/monorepo-private/pull/6230
> Transformations: remove line saying they are in beta

- docs/event-types.mdx
~~I'm still working on the examples for each lang.~~
~~I'm not fluent in most of these so it's taking a minute to make sure I'm not making nonsense examples.~~
Slimmed down the examples based on what we auto-generate for the API docs, leaving the reading of the JSON spec as an exercise for the reader 😉
> docs about event type import from openapi

- docs/receiving/verifying-payloads/how.mdx
adding example for Next 13 App Router
> Add Next.js 13 App Router example

- docs/integrations/ngrok.mdx
PM from ngrok here. I noticed this link was broken on your docs site.
> fix: Update broken link to ngrok webhook verification

- docs/receiving/verifying-payloads/how.mdx
added example for Node Fastify
> Add Node - Fastify example

- docs/app-portal.mdx
- Fixes the docs link
- Removes the assignment to a `useEffect`
> chore: update portal embed doc link and react code style

- docs/receiving/verifying-payloads/how.mdx
Follow-up to https://github.com/svix/svix-webhooks/issues/1463.
> Improve webhook verification examples for JS frameworks

- docs/receiving/receiving-with-ingest.mdx
This isn't complete but at least gets the idea across. We can add more
examples if we feel it's needed.
> Add some ingest code examples

- static/js/segment.js
Following the docs from https://posthog.com/docs/libraries/segment
> Add Posthog

- docs/receiving/receiving-with-ingest.mdx
UI PR: https://github.com/svix/monorepo-private/pull/10597
Backend PR: https://github.com/svix/svix-webhooks-private/pull/4182
> Add checkbook as a supported ingest provider

- docs/app-portal.mdx
Let's wait for github.com/svix/svix-webhooks-private/pull/4613 to be deployed.
> Update docs on app-portal-capabilities
