svix/svix-docs

docusaurus.config.js
sidebars.js

What do you think? Should it be called "API Documentation" or "API Reference", or what?

Rename: API Browser -> API Documentation.

---

docs/quickstart.mdx
docs/receiving/verifying-payloads/how.mdx

On initial load, these links gets treated as relative to the current page, but once cached they load fine, this issue only occurs with production-built versions of the site (not when served from `yarn start`.

Fix relative links on initial load

---

src/css/custom.css

This should remove the box-shadow on the top-left logo

Fix img tag css

---

src/css/custom.css

Before:
After:
There's a white box on the bottom of the sidebar.

Hide announcement bar

---

docusaurus.config.js

Added the gtag preset for Google Analytics Global Site Tag in the docusarus.config.js file.
trackingID is the Google Analytics account ID.
anonymizeIP tells Google Analytics to anonymize users' IP addresses for privacy.

add global site tag preset option in docusaurus config

---

docusaurus.config.js

Updated the trackingID in the gtag preset in docusaurus.config.js as we weren't seeing pageviews being tracked in Google Analytics.

Update GA ID

---

docs/app-portal.mdx

Adds a note about our new `next` query parameter to the docs.

`next` query parameter documentation

---

docs/app-portal.mdx

We recently began supporting a `fullSize` prop on `<AppPortal />` so that it grows to fit its contents. This PR just documents its existence.

svix-react: Document AppPortal fullSize prop

---

docs/app-portal.mdx

Updates the Consumer App Portal docs to mention the new
React Hooks available in the `svix-react` library, and how they
can be helpful in custom Portal development.

Add mention of React Hooks to docs

---

docs/app-portal.mdx

Adds documentation for the new environment-level read-only setting.
Also fixes a markdown formatting error for the React Hooks documentation.

Document environment-level setting for read-only Portals

---

docs/integrations/ngrok.mdx

Fixes a markdown typo causing the ngrok link to not render correctly.

Fix typo in Svix ngrok docs

---

docs/receiving/additional-authentication.mdx

fix typo in firewalls (ip blocking): conduction -> conjunction

typo: Update additional-authentication.mdx

---

docs/app-portal.mdx
docs/event-types.mdx

App portal access code examples use the new `app-portal-access` method. Event type docs introduce feature flags.

Update app portal access and event type docs

---

docs/tutorials/cli.mdx

We were linking to homebrew.sh instead of brew.sh

fix homebrew link

---

docs/common-usage-examples.mdx
docs/incoming-webhooks.mdx
docs/play.mdx
docs/receiving/using-app-portal/adding-endpoints.mdx
docs/receiving/verifying-payloads/how.mdx

Pretty much a straight find/replace.
~~Seems like we should have a redirect from the old `incoming-webhooks` url to the new `operational-webhooks` url, but I'm not sure if this should be done here, janky style, via a meta refresh (or similar). Might be better for SEO to handle the redirect as a proper 301 in whatever webserver is serving the static files.~~
Leaving the old `/incoming-webhooks` URL where it is for now.

rename "incoming webhooks" to "operational webhooks"

---

docs/event-types.mdx

Was going over the docs and noticed this one. "Make Publish" should be "Make Public".

Fix typo in event-types doc page

---

docs/event-types.mdx

`x-svix-eventTypeId` to `x-event-type`, just to make it nicer. Breaking the existing API since it has been out for a very short time. 
https://github.com/svix/monorepo-private/pull/5725

Change custom event type property for OpenAPI import

---

docs/event-types.mdx

We had a 'TBD' that was visible to customers so I added the code. I tested the example in my machine to make sure it actually works.
**Before**
**After**

Add Rust example for bulk upload event types

---

docs/quickstart.mdx

Because the examples lacked this type, people were mistakenly led to believe that they don't need to include the type in the payload.
Fixes #125

Quickstart: add webhook `type` to the example payloads

---

docs/app-portal.mdx
docs/event-types.mdx
docs/quickstart.mdx
docs/rate-limit.mdx
docs/receiving/verifying-payloads/how.mdx
docs/retention.md
docs/setup.mdx

Added missing parameters, changed incorrect types, removed erroneous braces, and passed everything through rustfmt on default settings.

Docs: repair types, syntax, formatting of rust examples

---

docs/account/org-members.mdx

I believe there's a typo in the number of supported roles.
I just updated it from two -> three

Update the number of supported roles

---

docs/event-types.mdx

As we've been doing more documentation reviews and releasing state of webhooks, it seems like we should be giving more recommendations on best practices to improve webhook consumers' developer experience.
The event catalog makes it easy for webook consumers to find the event types they want to subscribe to.

Add suggestion to add an event catalog to their documentation

---

docs/documentation.mdx
docs/documenting-webhooks.mdx
sidebars.js

At Svix, we consider our documentation to be part of the product. We should also take this stance for our customers and help them write their documentation.
This new section explains how to use the docs generator and event catalog.

add documentation section to the docs

---

docs/event-types.mdx
package.json
yarn.lock

Also added a resolution to fix the build in newer Node versions (similar to https://github.com/svix/www/pull/204)

Add Event Types Github Action to docs

---

.github/workflows/ci.yml
docs/event-types.mdx
docs/quickstart.mdx
docs/receiving/using-app-portal/testing-events.mdx
docs/receiving/verifying-payloads/how.mdx

First grammatical error may need review to check if the fix preserves the intention of the sentence. According to `git blame`, @tasn wrote it.

Fix typos, detect them in CI

---

docs/receiving/verifying-payloads/how.mdx
docs/setup.mdx

cc https://github.com/svix/svix-webhooks/issues/1245, I think the user who reported that issue might be on an outdated version of the client library because they copied the outdated dependency specification from our docs.

Improvements to Rust client library usage docs

---

docs/retries.mdx

We now mention the 12-24 hour window required for the second failure

Document current 'Endpoint disabled' behavior

---

docs/receiving/verifying-payloads/how-manual.mdx

This PR fixes the syntax error in the code snippet and updates the deprecated code `new Buffer`.

fix: update the code snippet

---

docs/event-types.mdx

Document https://github.com/svix/svix-webhooks-private/pull/2957

event types: add x-svix-feature-flags to OAS import docs

---

docs/receiving/verifying-payloads/how.mdx

The indentation is still inconsistent between different code samples (including different code samples using the same programming language), but that would be a much larger effort to fix, and we would first need to decide what indentation style to standardize on.

Fix inconsistent indentation within two code examples

---

docs/documenting-webhooks.mdx

re-write article to better highlight and explain all of our docs resources

Re-write docs article

---

docs/tutorials/connectors.mdx

… which were previously called transformation templates.

Update links to connectors

---

docs/receiving/verifying-payloads/how.mdx

The rust verification example should borrow the body and the headermap instead.
https://docs.rs/svix/latest/svix/webhooks/struct.Webhook.html#method.verify

Fix Rust verification example to borrow

---

docs/event-types.mdx
docs/integrations/advanced-zapier.mdx
docs/integrations/zapier.mdx
docs/polling-endpoints.mdx
docs/quickstart.mdx
docs/receiving/source-ips.mdx
docs/receiving/using-app-portal/adding-endpoints.mdx
docs/receiving/using-app-portal/polling-endpoints.mdx
docs/receiving/verifying-payloads/how.mdx
docs/security.mdx
docs/tutorials/connectors.mdx
docs/tutorials/event-type-schema.mdx

Admonitions with titles were not showing properly since the syntax was wrong (I think it changed in the newer version of docusaurus?). I did a search and replace to fix all of them. 
**Before**
**After**

Fix Admonition titles

---

docs/polling-endpoints.mdx
sidebars.js

To explain why you'd want to enable Polling Endpoints. 
I took Tom's text from https://www.svix.com/blog/turn-any-webhook-into-a-polling-api/ and reworded it a bit to fit it in the docs.
Also moved the Svix Play docs page to its own section so it's not buried under 'Additional links'

Add 'when is polling better' section to polling endpoints docs

---

docs/play.mdx

- Removed references to 'echo mode'
- Simplified the instructions. No need to visit www.svix.com/play.
- Moved 'programmatic usage' to the bottom of the doc since that's the most complex use case
Closes https://github.com/svix/monorepo-private/issues/9971

Simplify Svix Play docs

---

docs/advanced-endpoints/polling-endpoints.mdx
docs/receiving/verifying-payloads/receiving-with-bridge.mdx

Also adds some details about the consumer API to the polling endpoints docs.

Bridge: docs for the `svix-message-poller` receiver input

---

docs/app-portal.mdx

This closes https://github.com/svix/monorepo-private/issues/10474, by documenting the new session ID.

Document sessionID in the App Portal docs

---

docs/receiving/receiving-with-ingest.mdx

They were added in https://github.com/svix/svix-webhooks-private/pull/4329

Add new vapi, port.io and easypost ingest sources

---

docs/app-portal.mdx

- Remove useless self link
- Put main example first in own-app-portal section (`SvixProvider` usage after)
- Linkify first mention of `svix-react` instead of linking to it after the example

Improve app-portal page
